"""Serialising ``concept-graph.yaml`` — a derived artifact (ADR-001 §5).

Nick's ruling of 2026-07-30: this file is regenerated from the records'
canonical ``depends_on`` plus the bodies' usage edges, is never hand-edited,
and a hand-edit is a CI failure rather than a reconciliation problem. So the
rendering is byte-stable: every collection is sorted, key order is fixed, and
nothing derives from the filesystem or the clock.
"""

from __future__ import annotations

import yaml

from ..findings import Finding, error
from .build import ConceptGraph

SCHEMA = 1

HEADER = """\
# GENERATED by `detangle graph` — DO NOT HAND-EDIT.
#
# Derived from the canonical concept records (`concepts/*.yaml`,
# `depends_on`) and the canonical cycle register (`registers/cycles.yaml`).
# Nick's ruling of 2026-07-30 (ADR-001 Decision 5) makes this file derived:
# every edge in it is a copy of a record's `depends_on` or a usage edge
# extracted from a document body, so nothing canonical lives here. Edit the
# record, then regenerate — `detangle graph --check` fails on a hand-edit.
#
# Edge direction is `from` uses `to`: the definition of `from` uses the term
# `to`, so `to` must be defined first. `reading_order` is the topological
# sort of the reverse of that relation, with each accepted cycle condensed to
# one unit and its entry point placed first (criterion 1, clause 2).
"""

USAGE_NOTE = """\
  # Usage edges (C11, step 3.7) are extracted from the five document bodies,
  # which do not exist until Phase 5. Empty is the correct value now, not a
  # placeholder: the extraction that fills it is the same one the steady-state
  # drift lint re-runs on every later body edit (D10).
"""


def render(cg: ConceptGraph) -> str:
    """The full file, as text. Same inputs always give the same bytes."""
    cycles = []
    for cycle in cg.cycles:
        entry = cg.entry_for(cycle)
        rolled = {"members": list(cycle)}
        if entry is not None:
            rolled = {"id": entry.id, "members": list(cycle)}
            for key in ("disposition", "entry_point", "iso_704"):
                value = getattr(entry, key)
                if value is not None:
                    rolled[key] = value
            for key in ("rationale", "authority"):
                value = getattr(entry, key)
                if value is not None:
                    rolled[key] = value
        else:
            rolled["disposition"] = None
        cycles.append(rolled)

    edges = [
        {"from": u, "to": v} for u, v in sorted(cg.graph.edges())
    ]
    nodes = [
        {
            "id": rid,
            "term": cg.graph.nodes[rid]["term"],
            "placement": cg.graph.nodes[rid]["placement"],
            "defined": cg.graph.nodes[rid]["defined"],
        }
        for rid in sorted(cg.graph.nodes)
    ]
    orphans = cg.orphans()
    dead = cg.dead_entries()

    head = {
        "schema": SCHEMA,
        "generator": "detangle graph",
        "counts": {
            "nodes": len(nodes),
            "dependency_edges": len(edges),
            "usage_edges": 0,
            "cycles": len(cycles),
            "orphans": len(orphans),
            "undefined": len(cg.undefined()),
            "dead_entries": len(dead),
        },
        "cycles": cycles,
        "orphans": orphans,
        "dead_entries": dead,
        "reading_order": cg.reading_order(),
        "nodes": nodes,
    }

    parts = [HEADER, _dump(head), "\nedges:\n  dependency:\n"]
    parts.append(_dump(edges, indent=4) if edges else "    []\n")
    parts.append("  usage:\n")
    parts.append(USAGE_NOTE)
    parts.append("    []\n")
    return "".join(parts)


def _dump(data, indent: int = 0) -> str:
    text = yaml.safe_dump(
        data,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
        width=78,
    )
    if not indent:
        return text
    pad = " " * indent
    return "".join(
        pad + line if line.strip() else line for line in text.splitlines(True)
    )


def check_current(cg: ConceptGraph, path, rel: str) -> list[Finding]:
    """The regenerate-and-compare guard for this file.

    Compares bytes, not parsed structure: reordering a generated list changes
    nothing semantically and everything about whether the file was generated.
    """
    expected = render(cg)
    if not path.is_file():
        return [
            error(
                "graph-missing",
                rel,
                "no generated graph on disk; run `detangle graph` and commit it",
            )
        ]
    actual = path.read_text(encoding="utf-8")
    if actual != expected:
        return [
            error(
                "graph-drift",
                rel,
                "on-disk graph differs from a regeneration — it was hand-edited, "
                "or a record changed without regenerating. Run `detangle graph`",
            )
        ]
    return []


__all__ = ["SCHEMA", "check_current", "render"]
